"""add arrived_at to deliveries

Revision ID: 13151ab6c8d8
Revises: 9b3a77c6f2a1
Create Date: 2026-06-26 11:09:50.622501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13151ab6c8d8'
down_revision = '9b3a77c6f2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('arrived_at')

    # ### end Alembic commands ###
