"""Add quantity column to deliveries table

Revision ID: add_quantity_to_deliveries
Revises: add_notes_to_deliveries
Create Date: 2026-05-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_quantity_to_deliveries'
down_revision = 'add_notes_to_deliveries'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('quantity', sa.Integer(), nullable=True, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'quantity')
    # ### end Alembic commands ###
